### ISSUE TITLE
[Bug]: '"./main.js"' has no exported member 'run'.

### ISSUE THREAD

**Issue by gutenye** [targendaz2/jxa-runner#5]
### What did you expect to happen?

works

### What actually happened?

src/index.ts:2:10 - error TS2614: Module '"./main.js"' has no exported member 'run'. Did you mean to use 'import run from "./main.js"' instead?

2 export { run } from './main.js';
           ~~~

### How can you reproduce the bug?

yarn build

**Comment by targendaz2** [comment]
@gutenye this is still being developed.
